"""project-changes

Revision ID: 0f1054a001f7
Revises: b840210f190c
Create Date: 2024-08-20 06:02:57.043272

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f1054a001f7'
down_revision = 'b840210f190c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_environment',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('bh_env_id', sa.Integer(), nullable=False),
    sa.Column('bh_env_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bh_env_provider', sa.Integer(), nullable=False),
    sa.Column('cloud_provider_cd', sa.Integer(), nullable=False),
    sa.Column('cloud_region_cd', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pvt_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_cd', sa.Integer(), nullable=True),
    sa.Column('bh_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bh_env_provider'], ['catalogdb.codes_dtl.id'], ),
    sa.ForeignKeyConstraint(['bh_project_id'], ['catalogdb.bh_project.bh_project_id'], ),
    sa.PrimaryKeyConstraint('bh_env_id'),
    schema='catalogdb'
    )
    op.add_column('bh_project', sa.Column('bh_github_provider', sa.Integer(), nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_github_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_github_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_default_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_github_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_github_token_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.create_foreign_key(None, 'bh_project', 'codes_dtl', ['bh_github_provider'], ['id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.drop_column('bh_project', 'bh_project_desc', schema='catalogdb')
    op.drop_column('bh_project', 'bh_project_cld_id', schema='catalogdb')
    op.drop_column('bh_project', 'business_url', schema='catalogdb')
    op.drop_column('bh_project', 'lake_name', schema='catalogdb')
    op.drop_column('bh_project', 'env_cd', schema='catalogdb')
    op.drop_column('bh_project', 'lake_desc', schema='catalogdb')
    op.drop_column('bh_project', 'validation_status', schema='catalogdb')
    op.drop_column('bh_project', 'access_type_cd', schema='catalogdb')
    op.drop_column('bh_project', 'status_cd', schema='catalogdb')
    op.drop_column('bh_project', 'cloud_provider_cd', schema='catalogdb')
    op.drop_column('bh_project', 'access_details', schema='catalogdb')
    op.drop_column('bh_project', 'cloud_region_cd', schema='catalogdb')
    op.add_column('lake_zone', sa.Column('bh_env_id', sa.Integer(), nullable=True), schema='catalogdb')
    op.drop_constraint('lake_zone_bh_project_id_fkey', 'lake_zone', schema='catalogdb', type_='foreignkey')
    op.create_foreign_key(None, 'lake_zone', 'project_environment', ['bh_env_id'], ['bh_env_id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.drop_column('lake_zone', 'bh_project_id', schema='catalogdb')
    op.alter_column('publish_query_details', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publish_query_details', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='catalogdb')
    op.add_column('lake_zone', sa.Column('bh_project_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_constraint(None, 'lake_zone', schema='catalogdb', type_='foreignkey')
    op.create_foreign_key('lake_zone_bh_project_id_fkey', 'lake_zone', 'bh_project', ['bh_project_id'], ['bh_project_id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.drop_column('lake_zone', 'bh_env_id', schema='catalogdb')
    op.add_column('bh_project', sa.Column('cloud_region_cd', sa.INTEGER(), autoincrement=False, nullable=False), schema='catalogdb')
    op.add_column('bh_project', sa.Column('access_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('cloud_provider_cd', sa.INTEGER(), autoincrement=False, nullable=False), schema='catalogdb')
    op.add_column('bh_project', sa.Column('status_cd', sa.INTEGER(), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('access_type_cd', sa.INTEGER(), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('validation_status', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='catalogdb')
    op.add_column('bh_project', sa.Column('lake_desc', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('env_cd', sa.INTEGER(), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('lake_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('business_url', sa.VARCHAR(length=256), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_project_cld_id', sa.VARCHAR(), autoincrement=False, nullable=False), schema='catalogdb')
    op.add_column('bh_project', sa.Column('bh_project_desc', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_constraint(None, 'bh_project', schema='catalogdb', type_='foreignkey')
    op.drop_column('bh_project', 'bh_github_token_url', schema='catalogdb')
    op.drop_column('bh_project', 'bh_github_url', schema='catalogdb')
    op.drop_column('bh_project', 'bh_default_branch', schema='catalogdb')
    op.drop_column('bh_project', 'bh_github_email', schema='catalogdb')
    op.drop_column('bh_project', 'bh_github_username', schema='catalogdb')
    op.drop_column('bh_project', 'bh_github_provider', schema='catalogdb')
    op.drop_table('project_environment', schema='catalogdb')
    # ### end Alembic commands ###