"""changed_project_model_field

Revision ID: 1cce5012af0c
Revises: ac519dd89f32
Create Date: 2024-10-09 13:53:26.667430

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '1cce5012af0c'
down_revision = 'ac519dd89f32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bh_project', sa.Column('bh_github_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.drop_column('bh_project', 'github_org', schema='catalogdb')
    op.drop_constraint('flow_alert_created_by_fkey', 'flow_alert', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('flow_alert_updated_by_fkey', 'flow_alert', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('flow_connection_updated_by_fkey', 'flow_connection', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('flow_connection_created_by_fkey', 'flow_connection', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('flow_deployment_updated_by_fkey', 'flow_deployment', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('flow_deployment_created_by_fkey', 'flow_deployment', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_setting_created_by_fkey', 'pipeline_setting', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_setting_updated_by_fkey', 'pipeline_setting', schema='catalogdb', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pipeline_setting_updated_by_fkey', 'pipeline_setting', 'bh_user', ['updated_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_setting_created_by_fkey', 'pipeline_setting', 'bh_user', ['created_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('flow_deployment_created_by_fkey', 'flow_deployment', 'bh_user', ['created_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('flow_deployment_updated_by_fkey', 'flow_deployment', 'bh_user', ['updated_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('flow_connection_created_by_fkey', 'flow_connection', 'bh_user', ['created_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('flow_connection_updated_by_fkey', 'flow_connection', 'bh_user', ['updated_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('flow_alert_updated_by_fkey', 'flow_alert', 'bh_user', ['updated_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('flow_alert_created_by_fkey', 'flow_alert', 'bh_user', ['created_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.add_column('bh_project', sa.Column('github_org', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_column('bh_project', 'bh_github_username', schema='catalogdb')
    # ### end Alembic commands ###