"""publish_data

Revision ID: 255fc0ecce8e
Revises: a9a657994b67
Create Date: 2024-07-03 10:31:47.643009

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '255fc0ecce8e'
down_revision = 'a9a657994b67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_details',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('tag', sa.JSON(), nullable=True),
    sa.Column('schedule_details', sa.JSON(), nullable=True),
    sa.Column('alert_setting', sa.JSON(), nullable=True),
    sa.Column('publish_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bh_project_id', sa.Integer(), nullable=False),
    sa.Column('delivery_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('zone_cd', sa.Integer(), nullable=True),
    sa.Column('source_setup_cd', sa.Integer(), nullable=True),
    sa.Column('delivery_option_cd', sa.Integer(), nullable=True),
    sa.Column('file_format_cd', sa.Integer(), nullable=True),
    sa.Column('delimiter_cd', sa.Integer(), nullable=True),
    sa.Column('compression', sa.Integer(), nullable=True),
    sa.Column('delivery_type_cd', sa.Integer(), nullable=True),
    sa.Column('last_batch_id', sa.Integer(), nullable=True),
    sa.Column('last_batch_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_on', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['bh_project_id'], ['catalogdb.bh_project.bh_project_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['catalogdb.customer.customer_id'], ),
    sa.PrimaryKeyConstraint('publish_id'),
    schema='catalogdb'
    )
    op.create_table('publish_query_details',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_validated', sa.Boolean(), nullable=False),
    sa.Column('publish_id', sa.Integer(), nullable=True),
    sa.Column('is_save', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['publish_id'], ['catalogdb.publish_details.publish_id'], ),
    sa.PrimaryKeyConstraint('query_id'),
    schema='catalogdb'
    )
    op.add_column('connection_dtl', sa.Column('connection_details', sa.JSON(), nullable=True), schema='catalogdb')
    op.drop_column('connection_dtl', 'warehouse', schema='catalogdb')
    op.drop_column('connection_dtl', 'snow_flake_username', schema='catalogdb')
    op.drop_column('connection_dtl', 'snow_flake_url', schema='catalogdb')
    op.drop_column('connection_dtl', 'snow_flake_password', schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_dtl', sa.Column('snow_flake_password', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('connection_dtl', sa.Column('snow_flake_url', sa.VARCHAR(), autoincrement=False, nullable=False), schema='catalogdb')
    op.add_column('connection_dtl', sa.Column('snow_flake_username', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.add_column('connection_dtl', sa.Column('warehouse', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_column('connection_dtl', 'connection_details', schema='catalogdb')
    op.drop_table('publish_query_details', schema='catalogdb')
    op.drop_table('publish_details', schema='catalogdb')
    # ### end Alembic commands ###