"""upadate in pipeline and create release bundle

Revision ID: 46b122d91ad0
Revises: 37e8f7107286
Create Date: 2024-12-05 09:22:21.227643

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '46b122d91ad0'
down_revision = '37e8f7107286'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bh_bundle',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('bh_bundle_id', sa.Integer(), nullable=False),
    sa.Column('bh_bundle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bh_bundle_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bh_bundle_id'),
    schema='catalogdb'
    )
    op.create_table('pipeline_version',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('pipeline_version_id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_version_id'),
    schema='catalogdb'
    )
    op.create_table('pipeline_config',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('pipeline_config', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('pipeline_config_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['catalogdb.pipeline.pipeline_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_config_id'),
    schema='catalogdb'
    )
    op.add_column('flow', sa.Column('bh_bundle_id', sa.Integer(), nullable=True), schema='catalogdb')
    op.alter_column('flow', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='catalogdb')
    op.create_foreign_key(None, 'flow', 'bh_bundle', ['bh_bundle_id'], ['bh_bundle_id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.add_column('pipeline', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('pipeline', sa.Column('pipeline_version_id', sa.Integer(), nullable=True), schema='catalogdb')
    op.alter_column('pipeline', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='catalogdb')
    op.create_foreign_key(None, 'pipeline', 'pipeline_version', ['pipeline_version_id'], ['pipeline_version_id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.drop_column('pipeline', 'git_branch', schema='catalogdb')
    op.add_column('pipeline_definitions', sa.Column('schema_id', sa.Integer(), nullable=False), schema='catalogdb')
    op.create_foreign_key(None, 'pipeline_definitions', 'schema', ['schema_id'], ['schema_id'], source_schema='catalogdb', referent_schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_definitions', schema='catalogdb', type_='foreignkey')
    op.drop_column('pipeline_definitions', 'schema_id', schema='catalogdb')
    op.add_column('pipeline', sa.Column('git_branch', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_constraint(None, 'pipeline', schema='catalogdb', type_='foreignkey')
    op.alter_column('pipeline', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='catalogdb')
    op.drop_column('pipeline', 'pipeline_version_id', schema='catalogdb')
    op.drop_column('pipeline', 'notes', schema='catalogdb')
    op.drop_constraint(None, 'flow', schema='catalogdb', type_='foreignkey')
    op.alter_column('flow', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='catalogdb')
    op.drop_column('flow', 'bh_bundle_id', schema='catalogdb')
    op.drop_table('pipeline_config', schema='catalogdb')
    op.drop_table('pipeline_version', schema='catalogdb')
    op.drop_table('bh_bundle', schema='catalogdb')
    # ### end Alembic commands ###