"""added_fields_in_env_and_pipline_model

Revision ID: 4cded10f06cb
Revises: dd652955da22
Create Date: 2024-09-19 06:56:53.348201

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '4cded10f06cb'
down_revision = 'dd652955da22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('json_config', sa.JSON(), nullable=True), schema='catalogdb')
    op.add_column('project_environment', sa.Column('airflow_env_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('project_environment', sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_environment', 'access_key', schema='catalogdb')
    op.drop_column('project_environment', 'airflow_env_name', schema='catalogdb')
    op.drop_column('pipelines', 'json_config', schema='catalogdb')
    # ### end Alembic commands ###