"""add_parameter_type_to_pipeline_parameter

Revision ID: 53fc63f9dd24
Revises: 033d93d3f3bf
Create Date: 2025-02-20 01:38:59.123276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '53fc63f9dd24'
down_revision = '033d93d3f3bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_parameter', sa.Column('parameter_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='catalogdb')
    op.drop_constraint('pipeline_parameter_updated_by_fkey', 'pipeline_parameter', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_parameter_created_by_fkey', 'pipeline_parameter', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_parameter_deleted_by_fkey', 'pipeline_parameter', schema='catalogdb', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pipeline_parameter_deleted_by_fkey', 'pipeline_parameter', 'user_detail', ['deleted_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_parameter_created_by_fkey', 'pipeline_parameter', 'user_detail', ['created_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_parameter_updated_by_fkey', 'pipeline_parameter', 'user_detail', ['updated_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.drop_column('pipeline_parameter', 'parameter_type', schema='catalogdb')
    # ### end Alembic commands ###