"""release bundle relation with flow

Revision ID: 545a329cb7bb
Revises: 46b122d91ad0
Create Date: 2024-12-06 11:09:14.832704

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '545a329cb7bb'
down_revision = '46b122d91ad0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bh_bundle_created_by_fkey', 'bh_bundle', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('bh_bundle_updated_by_fkey', 'bh_bundle', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('bh_bundle_deleted_by_fkey', 'bh_bundle', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_config_updated_by_fkey', 'pipeline_config', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_config_deleted_by_fkey', 'pipeline_config', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_config_created_by_fkey', 'pipeline_config', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_version_created_by_fkey', 'pipeline_version', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_version_updated_by_fkey', 'pipeline_version', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_version_deleted_by_fkey', 'pipeline_version', schema='catalogdb', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pipeline_version_deleted_by_fkey', 'pipeline_version', 'user_detail', ['deleted_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_version_updated_by_fkey', 'pipeline_version', 'user_detail', ['updated_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_version_created_by_fkey', 'pipeline_version', 'user_detail', ['created_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_config_created_by_fkey', 'pipeline_config', 'user_detail', ['created_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_config_deleted_by_fkey', 'pipeline_config', 'user_detail', ['deleted_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_config_updated_by_fkey', 'pipeline_config', 'user_detail', ['updated_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('bh_bundle_deleted_by_fkey', 'bh_bundle', 'user_detail', ['deleted_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('bh_bundle_updated_by_fkey', 'bh_bundle', 'user_detail', ['updated_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('bh_bundle_created_by_fkey', 'bh_bundle', 'user_detail', ['created_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    # ### end Alembic commands ###