"""
created_pipeline_connection

Revision ID: 71dab3e3cadd
Revises: 0bfdd07644a4
Create Date: 2025-01-09 08:08:30.583973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '71dab3e3cadd'
down_revision = '0bfdd07644a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_connection',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('pipeline_connection_id', sa.Integer(), nullable=False),
    sa.Column('logical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bh_env_id', sa.Integer(), nullable=False),
    sa.Column('client_project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret_manager_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bh_env_id'], ['catalogdb.project_environment.bh_env_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_connection_id'),
    schema='catalogdb'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_connection', schema='catalogdb')
    # ### end Alembic commands ###