"""connection_config_and_registry

Revision ID: 7b25fd191bea
Revises: 1ce7f11dfa7f
Create Date: 2024-08-28 05:01:58.913657

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '7b25fd191bea'
down_revision = '1ce7f11dfa7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bh_connection_registry',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('connection_args', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_policies_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalogdb'
    )
    op.create_table('bh_connection_config',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_config_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('connection_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['catalogdb.bh_connection_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='catalogdb'
    )
    op.add_column('bh_project', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('project_environment', sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.drop_column('project_environment', 'gcp_project_id', schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_environment', sa.Column('gcp_project_id', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_column('project_environment', 'project_id', schema='catalogdb')
    op.drop_column('bh_project', 'status', schema='catalogdb')
    op.drop_table('bh_connection_config', schema='catalogdb')
    op.drop_table('bh_connection_registry', schema='catalogdb')
    # ### end Alembic commands ###