"""conn_registry_data_setup

Revision ID: 80dc2a3eebbd
Revises: bb9cdc669ca8
Create Date: 2024-09-04 11:02:03.239845

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80dc2a3eebbd'
down_revision = 'bb9cdc669ca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bh_connection_registry', 'connection_args', schema='catalogdb')
    op.drop_column('bh_connection_registry', 'connection_policies_description', schema='catalogdb')

    # Read SQL commands from file
    with open('migrations/sql/connection_registry_insert.sql') as sql_file:
        sql_commands = sql_file.read().split(';')
    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bh_connection_registry', sa.Column('connection_policies_description', sa.VARCHAR(), autoincrement=False, nullable=False), schema='catalogdb')
    op.add_column('bh_connection_registry', sa.Column('connection_args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False), schema='catalogdb')
    # ### end Alembic commands ###