"""flow table update

Revision ID: 8affe61676df
Revises: df269d0e1e99
Create Date: 2025-01-18 08:56:32.831887

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '8affe61676df'
down_revision = 'df269d0e1e99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with open('migrations/sql/flow_updated.sql') as sql_file:
        sql_commands = sql_file.read().split(';')

    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###