"""added_flow_id_in_flowversion

Revision ID: 8eab179d2fcc
Revises: adc392d3577e
Create Date: 2024-12-18 14:29:14.216102

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '8eab179d2fcc'
down_revision = 'adc392d3577e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_version', sa.Column('flow_id', sa.Integer(), nullable=True), schema='catalogdb')
    op.create_foreign_key(None, 'flow_version', 'flow', ['flow_id'], ['flow_id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.add_column('project_environment', sa.Column('bh_project_id', sa.Integer(), nullable=True), schema='catalogdb')
    op.create_foreign_key(None, 'project_environment', 'bh_project', ['bh_project_id'], ['bh_project_id'], source_schema='catalogdb', referent_schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_environment', schema='catalogdb', type_='foreignkey')
    op.drop_column('project_environment', 'bh_project_id', schema='catalogdb')
    op.drop_constraint(None, 'flow_version', schema='catalogdb', type_='foreignkey')
    op.drop_column('flow_version', 'flow_id', schema='catalogdb')
    # ### end Alembic commands ###