"""update_connection_registry_v2

Revision ID: 931d63dbe67b
Revises: 68eb1f429004
Create Date: 2025-03-19 07:14:07.509228

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '931d63dbe67b'
down_revision = '68eb1f429004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with open('migrations/sql/update_connectionregistry.sql') as sql_file:
        sql_commands = sql_file.read().split(';')

    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###