"""calatlogdb_query

Revision ID: 9722e08d8816
Revises: 8eab179d2fcc
Create Date: 2024-12-27 10:27:21.344921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '9722e08d8816'
down_revision = '8eab179d2fcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with open('migrations/sql/catalog_test.sql') as sql_file:
        sql_commands = sql_file.read().split(';')

    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###