"""lyt_multi_part

Revision ID: a9a657994b67
Revises: 98105a17e319
Create Date: 2024-06-08 11:47:07.626634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'a9a657994b67'
down_revision = '98105a17e319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_layout', sa.Column('data_src_multi_part_file', sa.Boolean(), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_source_layout', 'data_src_multi_part_file', schema='catalogdb')
    # ### end Alembic commands ###