"""flow_model_create

Revision ID: a9c481169590
Revises: 4cded10f06cb
Create Date: 2024-09-23 11:33:41.929275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'a9c481169590'
down_revision = '4cded10f06cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('json_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('flow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('git_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bh_project_id', sa.Integer(), nullable=True),
    sa.Column('bh_env_provider', sa.Integer(), nullable=False),
    sa.Column('flow_class', sa.Integer(), nullable=False),
    sa.Column('recipent_emails', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_executed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bh_env_provider'], ['catalogdb.codes_dtl.id'], ),
    sa.ForeignKeyConstraint(['bh_project_id'], ['catalogdb.bh_project.bh_project_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.bh_user.bh_user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_class'], ['catalogdb.codes_dtl.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.bh_user.bh_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flow_id'),
    schema='catalogdb'
    )
    op.create_table('schedule_interval',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('time', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.bh_user.bh_user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flow_id'], ['catalogdb.flow.flow_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.bh_user.bh_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_id'),
    schema='catalogdb'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_interval', schema='catalogdb')
    op.drop_table('flow', schema='catalogdb')
    # ### end Alembic commands ###