"""rule_recommendation

Revision ID: b338e8a320eb
Revises: 00821abaf61b
Create Date: 2024-05-01 12:21:23.847604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'b338e8a320eb'
down_revision = '00821abaf61b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fld_recommendations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('rule_params', sa.JSON(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('rule_dq_type_id', sa.Integer(), nullable=False),
    sa.Column('rule_dq_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_fld_id', sa.Integer(), nullable=True),
    sa.Column('rule_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_rejected_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_accepted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_lyt_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id'),
    schema='catalogdb'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fld_recommendations', schema='catalogdb')
    # ### end Alembic commands ###
