"""publish_data

Revision ID: b840210f190c
Revises: 255fc0ecce8e
Create Date: 2024-07-05 05:39:04.544666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'b840210f190c'
down_revision = '255fc0ecce8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_query_details', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publish_query_details', 'display_name', schema='catalogdb')
    # ### end Alembic commands ###