"""project_and_conn_registry_changes

Revision ID: bb9cdc669ca8
Revises: 5758a2bacf7d
Create Date: 2024-09-02 06:05:11.225618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'bb9cdc669ca8'
down_revision = '5758a2bacf7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bh_connection_registry', sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('data_source', sa.Column('connection_config_id', sa.Integer(), nullable=True), schema='catalogdb')
    op.create_foreign_key(None, 'data_source', 'bh_connection_config', ['connection_config_id'], ['id'], source_schema='catalogdb', referent_schema='catalogdb')
    op.add_column('project_environment', sa.Column('airflow_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('project_environment', sa.Column('airflow_bucket_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_environment', 'airflow_bucket_name', schema='catalogdb')
    op.drop_column('project_environment', 'airflow_url', schema='catalogdb')
    op.drop_constraint(None, 'data_source', schema='catalogdb', type_='foreignkey')
    op.drop_column('data_source', 'connection_config_id', schema='catalogdb')
    op.drop_column('bh_connection_registry', 'connection_type', schema='catalogdb')
    # ### end Alembic commands ###