"""dummy_data_for_schema_pipeline

Revision ID: bee8cbc65d91
Revises: 9722e08d8816
Create Date: 2025-01-02 06:40:47.817741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'bee8cbc65d91'
down_revision = '9722e08d8816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with open('migrations/sql/dummy_schema_pipeline_insert.sql') as sql_file:
        sql_commands = sql_file.read().split(';')

    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###