"""embedding_for_data_source_and_pipeline

Revision ID: d68577396724
Revises: 8affe61676df
Create Date: 2025-02-05 07:01:23.041071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
import pgvector

# revision identifiers, used by Alembic.
revision = 'd68577396724'
down_revision = '8affe61676df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('data_src_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True), schema='catalogdb')
    op.add_column('pipeline', sa.Column('pipeline_name_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'pipeline_name_embedding', schema='catalogdb')
    op.drop_column('data_source', 'data_src_embedding', schema='catalogdb')
    # ### end Alembic commands ###