"""demo data add update

Revision ID: df269d0e1e99
Revises: e372387babd5
Create Date: 2025-01-10 16:26:16.917118

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'df269d0e1e99'
down_revision = 'e372387babd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1: Read SQL commands from the file "CMDB Inserts"
    with open('migrations/sql/data_source_quality.sql') as sql_file:
        sql_commands = sql_file.read().split(';')

    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)
            
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###