"""demo data add

Revision ID: e372387babd5
Revises: 71dab3e3cadd
Create Date: 2025-01-10 05:50:29.484080

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'e372387babd5'
down_revision = '71dab3e3cadd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pipeline_connection_updated_by_fkey', 'pipeline_connection', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_connection_deleted_by_fkey', 'pipeline_connection', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pipeline_connection_created_by_fkey', 'pipeline_connection', schema='catalogdb', type_='foreignkey')
    
    # 1: Read SQL commands from the file "CMDB Inserts"
    with open('migrations/sql/demo_data_setup.sql') as sql_file:
        sql_commands = sql_file.read().split(';')

    # Execute each command separately
    for command in sql_commands:
        if command.strip():
            op.execute(command)
            
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pipeline_connection_created_by_fkey', 'pipeline_connection', 'user_detail', ['created_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_connection_deleted_by_fkey', 'pipeline_connection', 'user_detail', ['deleted_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pipeline_connection_updated_by_fkey', 'pipeline_connection', 'user_detail', ['updated_by'], ['user_detail_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    # ### end Alembic commands ###