"""changes_in_datasource_table


Revision ID: e57df5e9e5d1
Revises: 0d0a9fae4db9
Create Date: 2025-02-26 16:01:26.636882

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'e57df5e9e5d1'
down_revision = '0d0a9fae4db9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source', sa.Column('data_src_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.drop_column('data_source', 'connection_type', schema='catalogdb')
    op.add_column('data_source_layout', sa.Column('data_src_lyt_encoding', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.drop_column('data_source_layout', 'data_src_lyt_encoding_cd', schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_source_layout', sa.Column('data_src_lyt_encoding_cd', sa.INTEGER(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_column('data_source_layout', 'data_src_lyt_encoding', schema='catalogdb')
    op.add_column('data_source', sa.Column('connection_type', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_column('data_source', 'data_src_status', schema='catalogdb')
    # ### end Alembic commands ###