"""adding pipeline parameters

Revision ID: e992778b14c9
Revises: d68577396724
Create Date: 2025-02-16 17:08:01.288637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'e992778b14c9'
down_revision = 'd68577396724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_parameter',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('pipeline_parameter_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['catalogdb.pipeline.pipeline_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['catalogdb.user_detail.user_detail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_parameter_id'),
    schema='catalogdb'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_parameter', schema='catalogdb')
    # ### end Alembic commands ###