"""changed_flow_model_f_field

Revision ID: e9d608a40e5d
Revises: c64d620e9f68
Create Date: 2024-09-26 06:49:23.773796

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9d608a40e5d'
down_revision = 'c64d620e9f68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('configure_lifecycle_created_by_fkey', 'configure_lifecycle', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('configure_lifecycle_updated_by_fkey', 'configure_lifecycle', schema='catalogdb', type_='foreignkey')
    op.add_column('flow', sa.Column('metadata_flow', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.drop_column('flow', 'flow_metadata', schema='catalogdb')
    op.drop_constraint('pre_configure_zone_created_by_fkey', 'pre_configure_zone', schema='catalogdb', type_='foreignkey')
    op.drop_constraint('pre_configure_zone_updated_by_fkey', 'pre_configure_zone', schema='catalogdb', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('pre_configure_zone_updated_by_fkey', 'pre_configure_zone', 'bh_user', ['updated_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('pre_configure_zone_created_by_fkey', 'pre_configure_zone', 'bh_user', ['created_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.add_column('flow', sa.Column('flow_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='catalogdb')
    op.drop_column('flow', 'metadata_flow', schema='catalogdb')
    op.create_foreign_key('configure_lifecycle_updated_by_fkey', 'configure_lifecycle', 'bh_user', ['updated_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    op.create_foreign_key('configure_lifecycle_created_by_fkey', 'configure_lifecycle', 'bh_user', ['created_by'], ['bh_user_id'], source_schema='catalogdb', referent_schema='catalogdb', ondelete='CASCADE')
    # ### end Alembic commands ###