"""added display name in connection registry

Revision ID: ed1a63e78505
Revises: 1cce5012af0c
Create Date: 2024-10-15 10:11:43.045358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'ed1a63e78505'
down_revision = '1cce5012af0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bh_connection_registry', sa.Column('connection_display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bh_connection_registry', 'connection_display_name', schema='catalogdb')
    # ### end Alembic commands ###