"""conn_config_changes

Revision ID: fc88232d03be
Revises: 80dc2a3eebbd
Create Date: 2024-09-10 14:01:48.390021

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'fc88232d03be'
down_revision = '80dc2a3eebbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bh_connection_config', sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('bh_connection_config', sa.Column('connection_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    op.add_column('bh_connection_config', sa.Column('data_residency', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='catalogdb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bh_connection_config', 'data_residency', schema='catalogdb')
    op.drop_column('bh_connection_config', 'connection_status', schema='catalogdb')
    op.drop_column('bh_connection_config', 'connection_type', schema='catalogdb')
    # ### end Alembic commands ###