INSERT INTO catalogdb.bh_connection_registry (id, connection_name, connection_description, connection_type, connection_display_name) 
VALUES 
    (1018, 'ibm_db2', 'IBM DB2 database connection', 'source', 'IBM DB2'),
    (1019, 'ibm_db2', 'IBM DB2 database connection', 'destination', 'IBM DB2'),
    (1020, 'ibm_idms', 'IBM IDMS database connection', 'source', 'IBM IDMS'),
    (1021,  'ibm_idms', 'IBM IDMS database connection', 'destination', 'IBM IDMS'),
    (1022, 'databricks_lakehouse', 'Databricks Lakehouse connection for analytics', 'source', 'Databricks Lakehouse'),
    (1023, 'ms_sql_server', 'Microsoft SQL Server database connection', 'source', 'MS SQL Server'),
    (1024, 'pinecone', 'Pinecone vector database connection', 'source', 'Pinecone'),
    (1025, 'redshift', 'Amazon Redshift data warehouse connection', 'source', 'Redshift'),
    (1026, 'salesforce', 'Salesforce CRM data connection', 'source', 'Salesforce'),
    (1027, 'weaviate', 'Weaviate vector search engine connection', 'source', 'Weaviate'),
    (1028, 'apache_iceberg', 'Apache Iceberg table format connection', 'source', 'Apache Iceberg'),
    (1029, 'azure_blob_storage', 'Azure Blob Storage data connection', 'source', 'Azure Blob Storage'),
    (1030, 'clickhouse', 'ClickHouse OLAP database connection', 'source', 'Clickhouse'),
    (1031, 'duckdb', 'DuckDB in-process SQL database connection', 'source', 'DuckDB'),
    (1032, 'dynamodb', 'Amazon DynamoDB NoSQL database connection', 'source', 'DynamoDB'),
    (1033, 'elasticsearch', 'Elasticsearch search and analytics engine connection', 'source', 'ElasticSearch'),
    (1034, 'google_firestore', 'Google Firestore NoSQL database connection', 'source', 'Google Firestore'),
    (1035, 'google_pubsub', 'Google Pub/Sub messaging system connection', 'source', 'Google PubSub'),
    (1036, 'google_sheets', 'Google Sheets data source connection', 'source', 'Google Sheets'),
    (1037, 'kafka', 'Apache Kafka message queue connection', 'source', 'Kafka'),
    (1038, 'mongodb', 'MongoDB NoSQL database connection', 'source', 'MongoDB'),
    (1039, 'redis', 'Redis in-memory data structure store connection', 'source', 'Redis'),
    (1040, 'starburst_galaxy', 'Starburst Galaxy distributed SQL query engine connection', 'source', 'Starburst Galaxy'),
    (1041, 'databricks_lakehouse', 'Databricks Lakehouse connection for analytics', 'destination', 'Databricks Lakehouse'),
    (1042, 'ms_sql_server', 'Microsoft SQL Server database connection', 'destination', 'MS SQL Server'),
    (1043, 'pinecone', 'Pinecone vector database connection', 'destination', 'Pinecone'),
    (1044, 'redshift', 'Amazon Redshift data warehouse connection', 'destination', 'Redshift'),
    (1045, 'salesforce', 'Salesforce CRM data connection', 'destination', 'Salesforce'),
    (1046, 'weaviate', 'Weaviate vector search engine connection', 'destination', 'Weaviate'),
    (1047, 'apache_iceberg', 'Apache Iceberg table format connection', 'destination', 'Apache Iceberg'),
    (1048, 'azure_blob_storage', 'Azure Blob Storage data connection', 'destination', 'Azure Blob Storage'),
    (1049, 'clickhouse', 'ClickHouse OLAP database connection', 'destination', 'Clickhouse'),
    (1050, 'duckdb', 'DuckDB in-process SQL database connection', 'destination', 'DuckDB'),
    (1051, 'dynamodb', 'Amazon DynamoDB NoSQL database connection', 'destination', 'DynamoDB'),
    (1052, 'elasticsearch', 'Elasticsearch search and analytics engine connection', 'destination', 'ElasticSearch'),
    (1053, 'google_firestore', 'Google Firestore NoSQL database connection', 'destination', 'Google Firestore'),
    (1054, 'google_pubsub', 'Google Pub/Sub messaging system connection', 'destination', 'Google PubSub'),
    (1055, 'google_sheets', 'Google Sheets data source connection', 'destination', 'Google Sheets'),
    (1056, 'kafka', 'Apache Kafka message queue connection', 'destination', 'Kafka'),
    (1057, 'mongodb', 'MongoDB NoSQL database connection', 'destination', 'MongoDB'),
    (1058, 'redis', 'Redis in-memory data structure store connection', 'destination', 'Redis'),
    (1059, 'starburst_galaxy', 'Starburst Galaxy distributed SQL query engine connection', 'destination', 'Starburst Galaxy');

