
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (1, 'Datatype', null, null, null);
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (2, 'Maximum Length', 'length({{field}}) <= {{value1}}', null, '{"value1": "Integer"}');
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (3, 'Minimum Length', 'length({{field}}) >= {{value1}}', null, '{"value1": "Integer"}');
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (4, 'Date Format', null, '{"lookup_list": ["YYYYMMDD", "YYMMDD", "CCYYMMDD", "YYYY-MM-DD", "YY-MM-DD", "CCYY-MM-DD", "YYYY/MM/DD", "YY/MM/DD", "CCYY/MM/DD", "YYYYDDMM", "YYDDMM", "MM/DD/YYYY", "MMDDYYYY", "YYYY-MM-DD", "YYDDD", "YYYYDDD", "MM/DD/YYYY HH:MM", "MM/DD/YYYY HH:MI", "DD-MMM-YYYY", "DD MMM YYYY", "MMM DD YYYY", "MM-DD-YYYY", "MM/DD/YYYY HH:MM:SS", "MM/DD/YYYY HH:MI:SS", "YYYY-MM-DDTHH:MI:SS", "YYYY-MM-DDTHH:MM:SS", "YYYY-MM-DD HH:MM:SS", "YYYY-MM-DD HH:MI:SS", "MM/DD/YYYY H:M:S AM", "MM/DD/YYYY H:M:S PM", "MM/DD/YYYY H:M:S AM/PM", "MM/DD/YYYY H:MI:SS AM/PM", "MM/DD/YYYY HH:MI:SS AM/PM", "MM/DD/YYYY HH:MM:SS AM/PM", "MMM DD YYYY H:M:SPM", "MMM DD YYYY H:M:SAM", "MMM DD YYYY H:M:SAM/PM", "MMM DD YYYY H:M:S AM/PM", "MMM DD YYYY H:MAM/PM", "MMM DD YYYY H:M AM/PM", "YYYYMMDD H:M:S AM/PM", "YYYYMMDD H:M AM/PM", "YYYYMMDD HH:MI:SS", "YYYYMMDD HH:MM:SS", "YYYY-MM-DDTHH:MM:SS.MS-HH:MM", "YYYY-MM-DDTHH:MM:SS.MS+HH:MM"]}', null);
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (5, 'Length Range', '{{value1}} >= length({{field}}) <= {{value2}}', null, '{"value1": "Integer", "value2": "Integer"}');
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (6, 'Mandatory', '{{field}} IS NOT NULL', null, '{"value1": "String"}');
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (7, 'Valid Values', '{{field}} IN ({{value1}})', null, '{"value1": "String"}');
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (8, 'Value Range', '{{value1}} >= {{field}} <= {{value2}}', null, '{"value1": "Integer", "value2": "Integer"}');
INSERT INTO fld_dq_types (dq_id, dq_name, dq_template, dq_lookup, dq_inputs) VALUES (9, 'Custom Validation', '{{SQL_CONDITION}}', null, '{"SQL_CONDITION": "SQL"}');
