# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/data.proto\x12\x04\x64\x61ta\"\x94\x01\n\x15TransformationRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\x12\x1b\n\x13transformation_name\x18\x02 \x01(\t\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12&\n\x0csort_columns\x18\x05 \x03(\x0b\x32\x10.data.SortColumn\")\n\nSortColumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\t\"U\n\x03Row\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.data.Row.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"/\n\x06Output\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x04rows\x18\x02 \x03(\x0b\x32\t.data.Row\"Z\n\x1cTransformationOutputResponse\x12\x1b\n\x13transformation_name\x18\x01 \x01(\t\x12\x1d\n\x07outputs\x18\x02 \x03(\x0b\x32\x0c.data.Output\"=\n$GetTransformationOutputCountsRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\"K\n\x19TransformationOutputCount\x12\x1b\n\x13transformation_name\x18\x01 \x01(\t\x12\x11\n\trow_count\x18\x02 \x01(\x03\"n\n%GetTransformationOutputCountsResponse\x12\x45\n\x1ctransformation_output_counts\x18\x01 \x03(\x0b\x32\x1f.data.TransformationOutputCount2\xe3\x01\n\x0b\x44\x61taService\x12Z\n\x17GetTransformationOutput\x12\x1b.data.TransformationRequest\x1a\".data.TransformationOutputResponse\x12x\n\x1dGetTransformationOutputCounts\x12*.data.GetTransformationOutputCountsRequest\x1a+.data.GetTransformationOutputCountsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROW_DATAENTRY']._loaded_options = None
  _globals['_ROW_DATAENTRY']._serialized_options = b'8\001'
  _globals['_TRANSFORMATIONREQUEST']._serialized_start=28
  _globals['_TRANSFORMATIONREQUEST']._serialized_end=176
  _globals['_SORTCOLUMN']._serialized_start=178
  _globals['_SORTCOLUMN']._serialized_end=219
  _globals['_ROW']._serialized_start=221
  _globals['_ROW']._serialized_end=306
  _globals['_ROW_DATAENTRY']._serialized_start=263
  _globals['_ROW_DATAENTRY']._serialized_end=306
  _globals['_OUTPUT']._serialized_start=308
  _globals['_OUTPUT']._serialized_end=355
  _globals['_TRANSFORMATIONOUTPUTRESPONSE']._serialized_start=357
  _globals['_TRANSFORMATIONOUTPUTRESPONSE']._serialized_end=447
  _globals['_GETTRANSFORMATIONOUTPUTCOUNTSREQUEST']._serialized_start=449
  _globals['_GETTRANSFORMATIONOUTPUTCOUNTSREQUEST']._serialized_end=510
  _globals['_TRANSFORMATIONOUTPUTCOUNT']._serialized_start=512
  _globals['_TRANSFORMATIONOUTPUTCOUNT']._serialized_end=587
  _globals['_GETTRANSFORMATIONOUTPUTCOUNTSRESPONSE']._serialized_start=589
  _globals['_GETTRANSFORMATIONOUTPUTCOUNTSRESPONSE']._serialized_end=699
  _globals['_DATASERVICE']._serialized_start=702
  _globals['_DATASERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
