# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import data_pb2 as protos_dot_data__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransformationOutput = channel.unary_unary(
                '/data.DataService/GetTransformationOutput',
                request_serializer=protos_dot_data__pb2.TransformationRequest.SerializeToString,
                response_deserializer=protos_dot_data__pb2.TransformationOutputResponse.FromString,
                _registered_method=True)
        self.GetTransformationOutputCounts = channel.unary_unary(
                '/data.DataService/GetTransformationOutputCounts',
                request_serializer=protos_dot_data__pb2.GetTransformationOutputCountsRequest.SerializeToString,
                response_deserializer=protos_dot_data__pb2.GetTransformationOutputCountsResponse.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTransformationOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransformationOutputCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransformationOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransformationOutput,
                    request_deserializer=protos_dot_data__pb2.TransformationRequest.FromString,
                    response_serializer=protos_dot_data__pb2.TransformationOutputResponse.SerializeToString,
            ),
            'GetTransformationOutputCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransformationOutputCounts,
                    request_deserializer=protos_dot_data__pb2.GetTransformationOutputCountsRequest.FromString,
                    response_serializer=protos_dot_data__pb2.GetTransformationOutputCountsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    # server.add_registered_method_handlers('data.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTransformationOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/GetTransformationOutput',
            protos_dot_data__pb2.TransformationRequest.SerializeToString,
            protos_dot_data__pb2.TransformationOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransformationOutputCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data.DataService/GetTransformationOutputCounts',
            protos_dot_data__pb2.GetTransformationOutputCountsRequest.SerializeToString,
            protos_dot_data__pb2.GetTransformationOutputCountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
