# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/log.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/log.proto\x12\x03log\"#\n\nLogRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\"\x1f\n\x0bLogResponse\x12\x10\n\x08log_line\x18\x01 \x01(\t2?\n\nLogService\x12\x31\n\nStreamLogs\x12\x0f.log.LogRequest\x1a\x10.log.LogResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=25
  _globals['_LOGREQUEST']._serialized_end=60
  _globals['_LOGRESPONSE']._serialized_start=62
  _globals['_LOGRESPONSE']._serialized_end=93
  _globals['_LOGSERVICE']._serialized_start=95
  _globals['_LOGSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
