# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline_operations.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protos/pipeline_operations.proto\x12\x13pipeline_operations\"g\n\x14StartPipelineRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\x12\x15\n\rpipeline_json\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\x13\n\x0b\x63heckpoints\x18\x04 \x03(\t\",\n\x13StopPipelineRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\".\n\x15NextCheckpointRequest\x12\x15\n\rpipeline_name\x18\x01 \x01(\t\"#\n\x10PipelineResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc4\x02\n\x19PipelineOperationsService\x12\x61\n\rStartPipeline\x12).pipeline_operations.StartPipelineRequest\x1a%.pipeline_operations.PipelineResponse\x12_\n\x0cStopPipeline\x12(.pipeline_operations.StopPipelineRequest\x1a%.pipeline_operations.PipelineResponse\x12\x63\n\x0eNextCheckpoint\x12*.pipeline_operations.NextCheckpointRequest\x1a%.pipeline_operations.PipelineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.pipeline_operations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTPIPELINEREQUEST']._serialized_start=57
  _globals['_STARTPIPELINEREQUEST']._serialized_end=160
  _globals['_STOPPIPELINEREQUEST']._serialized_start=162
  _globals['_STOPPIPELINEREQUEST']._serialized_end=206
  _globals['_NEXTCHECKPOINTREQUEST']._serialized_start=208
  _globals['_NEXTCHECKPOINTREQUEST']._serialized_end=254
  _globals['_PIPELINERESPONSE']._serialized_start=256
  _globals['_PIPELINERESPONSE']._serialized_end=291
  _globals['_PIPELINEOPERATIONSSERVICE']._serialized_start=294
  _globals['_PIPELINEOPERATIONSSERVICE']._serialized_end=618
# @@protoc_insertion_point(module_scope)
