# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.protos import pipeline_operations_pb2 as protos_dot_pipeline__operations__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/pipeline_operations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PipelineOperationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPipeline = channel.unary_unary(
                '/pipeline_operations.PipelineOperationsService/StartPipeline',
                request_serializer=protos_dot_pipeline__operations__pb2.StartPipelineRequest.SerializeToString,
                response_deserializer=protos_dot_pipeline__operations__pb2.PipelineResponse.FromString,
                _registered_method=True)
        self.StopPipeline = channel.unary_unary(
                '/pipeline_operations.PipelineOperationsService/StopPipeline',
                request_serializer=protos_dot_pipeline__operations__pb2.StopPipelineRequest.SerializeToString,
                response_deserializer=protos_dot_pipeline__operations__pb2.PipelineResponse.FromString,
                _registered_method=True)
        self.NextCheckpoint = channel.unary_unary(
                '/pipeline_operations.PipelineOperationsService/NextCheckpoint',
                request_serializer=protos_dot_pipeline__operations__pb2.NextCheckpointRequest.SerializeToString,
                response_deserializer=protos_dot_pipeline__operations__pb2.PipelineResponse.FromString,
                _registered_method=True)


class PipelineOperationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineOperationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPipeline,
                    request_deserializer=protos_dot_pipeline__operations__pb2.StartPipelineRequest.FromString,
                    response_serializer=protos_dot_pipeline__operations__pb2.PipelineResponse.SerializeToString,
            ),
            'StopPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPipeline,
                    request_deserializer=protos_dot_pipeline__operations__pb2.StopPipelineRequest.FromString,
                    response_serializer=protos_dot_pipeline__operations__pb2.PipelineResponse.SerializeToString,
            ),
            'NextCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.NextCheckpoint,
                    request_deserializer=protos_dot_pipeline__operations__pb2.NextCheckpointRequest.FromString,
                    response_serializer=protos_dot_pipeline__operations__pb2.PipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline_operations.PipelineOperationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    # server.add_registered_method_handlers('pipeline_operations.PipelineOperationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineOperationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline_operations.PipelineOperationsService/StartPipeline',
            protos_dot_pipeline__operations__pb2.StartPipelineRequest.SerializeToString,
            protos_dot_pipeline__operations__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline_operations.PipelineOperationsService/StopPipeline',
            protos_dot_pipeline__operations__pb2.StopPipelineRequest.SerializeToString,
            protos_dot_pipeline__operations__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NextCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline_operations.PipelineOperationsService/NextCheckpoint',
            protos_dot_pipeline__operations__pb2.NextCheckpointRequest.SerializeToString,
            protos_dot_pipeline__operations__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
